# Generated by Django 5.2.8 on 2025-11-15 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_appuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.AddField(
            model_name='appuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=120)),
                ('lifecycle', models.CharField(choices=[('Active', 'Active'), ('Listed', 'Listed'), ('Sold', 'Sold'), ('Donated', 'Donated'), ('Discarded', 'Discarded')], default='Active', max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('size_label', models.CharField(blank=True, max_length=20)),
                ('material', models.CharField(blank=True, max_length=60)),
                ('color', models.CharField(blank=True, max_length=40)),
                ('season_hint', models.CharField(blank=True, choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter'), ('All', 'All')], max_length=20)),
                ('condition', models.CharField(blank=True, choices=[('New', 'New'), ('LikeNew', 'LikeNew'), ('Good', 'Good'), ('Fair', 'Fair'), ('Worn', 'Worn')], max_length=20)),
                ('image_url', models.TextField(blank=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_user.brand')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='app_user.category')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app_user.appuser')),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('listed_on', models.DateField(auto_now_add=True)),
                ('list_price_cents', models.IntegerField()),
                ('status', models.CharField(default='Active', max_length=20)),
                ('view_count', models.IntegerField(default=0)),
                ('buyer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='app_user.appuser')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.item')),
                ('seller_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.appuser')),
            ],
            options={
                'db_table': 'listing',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_type', models.CharField(choices=[('Retail', 'Retail'), ('LocalMarket', 'LocalMarket'), ('SecondHand', 'SecondHand'), ('Gift', 'Gift')], max_length=20)),
                ('price_cents', models.IntegerField()),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=80, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_user.item')),
            ],
            options={
                'db_table': 'purchase',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('sold_on', models.DateField(auto_now_add=True)),
                ('sale_price_cents', models.IntegerField()),
                ('buyer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.appuser')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.listing')),
            ],
            options={
                'db_table': 'sale',
            },
        ),
    ]
