# Generated by Django 5.2.8 on 2025-11-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_brand_category_appuser_email_item_listing_purchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.TextField(blank=True, db_column='item_image'),
        ),
    ]
