# Generated by Django 5.2.8 on 2025-11-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_alter_item_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='id',
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
