# Generated by Django 5.2.8 on 2025-11-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0005_remove_brand_id_brand_brand_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='id',
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
