# Generated by Django 5.2.8 on 2025-11-16 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0006_remove_purchase_id_purchase_purchase_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='seller_user',
        ),
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(blank=True, db_column='brand_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_user.brand'),
        ),
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('LikeNew', 'LikeNew'), ('Good', 'Good'), ('Fair', 'Fair'), ('Worn', 'Worn')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='lifecycle',
            field=models.CharField(choices=[('Wardrobe', 'Wardrobe'), ('Listed', 'Listed'), ('Sold', 'Sold'), ('Donated', 'Donated'), ('Discarded', 'Discarded')], default='Wardrobe', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='season_hint',
            field=models.CharField(blank=True, choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter'), ('All', 'All')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='item',
            field=models.OneToOneField(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='app_user.item'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='item',
            field=models.OneToOneField(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='app_user.item'),
        ),
    ]
