# Generated by Django 5.2.8 on 2025-11-17 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0007_remove_item_image_url_remove_listing_seller_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='seller_user',
            field=models.ForeignKey(db_column='seller_user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='app_user.appuser'),
            preserve_default=False,
        ),
    ]
