# Generated by Django 5.2.8 on 2025-11-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0008_listing_seller_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Like New', 'Like New'), ('Good', 'Good'), ('Fair', 'Fair'), ('Worn', 'Worn')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
