# Generated by Django 5.2.8 on 2025-11-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0009_alter_item_condition_alter_purchase_purchase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('LikeNew', 'LikeNew'), ('Good', 'Good'), ('Fair', 'Fair'), ('Worn', 'Worn')], max_length=20, null=True),
        ),
    ]
